### ISSUE TITLE
0.8.3.4 fails to build with ghc-8.2 due to missing <>

### ISSUE THREAD

**Issue by juhp** [aesiniath/http-common#16]
http-common-0.8.3.4 fails to build with ghc-8.2.2:

```
lib/Network/Http/Internal.hs:291:13: error:
Error:     • Variable not in scope: (<>) :: Builder -> Builder -> t7
    • Perhaps you meant one of these:
        ‘<’ (imported from Prelude), ‘<$>’ (imported from Prelude),
        ‘*>’ (imported from Prelude)
    |
291 |             <> dashdash
    |             ^^

lib/Network/Http/Internal.hs:292:13: error:
Error:     • Variable not in scope: (<>) :: t7 -> Builder -> t6
    • Perhaps you meant one of these:
        ‘<’ (imported from Prelude), ‘<$>’ (imported from Prelude),
        ‘*>’ (imported from Prelude)
    |
292 |             <> Builder.copyByteString (unBoundary boundary)
    |             ^^
: 
:
```

I appreciate you might not want to support this library any longer for ghc <= 8.2,
but then it would be good to revise the .cabal file to prevent
this version (and later) from being selected on 8.2.
I _think_ the easiest way to do that would be to add a lower bound for base.
Happy to open a PR to do that.
